# -*- coding: utf-8 -*-
"""countByKey .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJpqVxevOfjZFSn7oUQG7JmaSVRKdWdg
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Ejemplo RDD").getOrCreate()

sc = spark.sparkContext

pares = [("a", 1), ("b", 1), ("a", 1), ("c", 1), ("b", 1), ("a", 1)]

rdd_pares = sc.parallelize(pares)

conteo_claves = rdd_pares.countByKey()

print(dict(conteo_claves))