# -*- coding: utf-8 -*-
"""ejemplo_foreach.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srWeJvxi-SQM0IYBcRUpzs1vARMuW__i
"""

from pyspark import SparkContext

sc = SparkContext("local", "Foreach_ejemplo")

datos = [7, 8, 9, 4, 5]

rdd = sc.parallelize(datos)

def imprimir(elemento):
   print("Elemento:", elemento)

rdd.foreach(imprimir)

sc.stop()