# -*- coding: utf-8 -*-
"""ejemplo_first.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LcwvBhH0MGOB0zIrpeyI0q7-Dh8h0Orz
"""

from pyspark import SparkContext

sc = SparkContext("local", "First_ejemplo")

data = ["soy primero", "hola", "buenas", "lol", "local"]

rdd = sc.parallelize(data)

primer_element = rdd.first()

print("El primer elemento es:", primer_element)