# -*- coding: utf-8 -*-
"""ejemplo_COLLECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JcriYzg5ZPUS1WvMgj-YCt-cOUUTzEG
"""

from pyspark import SparkContext

datos = ["hola", "buenos", "dias", "y", "noches"]

rdd = sc.parallelize(datos)

resultado = rdd.collect()

print("Los elementos del RDD son:", resultado)