# -*- coding: utf-8 -*-
"""saveAsTextFile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DeOUXDeCvJ6hqzoLyvrWNk9YsrXswuuZ
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Ejemplo RDD").getOrCreate()

sc = spark.sparkContext

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

rdd_numeros = sc.parallelize(numeros)

rdd_numeros.saveAsTextFile("output/numeros.txt")

!ls output

import shutil

shutil.make_archive('numeros', 'zip', 'output')